# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20171224_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
